#goal
float64 x
float64 y
float64 z

float64 orx
float64 ory
float64 orz
float64 orw
int32 operation
int32 id
apriltag_ros/AprilTagDetection atdetection
---
#Result definition
geometry_msgs/Point[] obstacles
bool arrivedstatus
---
#feedback
float64 actualX
float64 actualY
uint8 state                     
int32[] color_ids